config/routes.rb
Rails.application.routes.draw do
  resources :posts do
    collection do
      post :confirm
    end
  end 
  resources :sessions, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create, :show]
  root 'users#new'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  mount_uploader :image, ImageUploader
  belongs_to :user
  validates :image, :content, presence: true
end

app/models/user.rb
class User < ApplicationRecord
    validates :name,  presence: true, length: { maximum: 30 }
    validates :email, presence: true, length: { maximum: 255 },
                      format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
    before_validation { email.downcase! }
    has_secure_password
    validates :password, presence: true, length: { minimum: 6 }
    has_many :posts, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
    include SessionsHelper
    before_action :login_required
    private
    def login_required
      redirect_to new_session_path unless current_user
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]
  def index
    @posts = Post.all
  end

  def show
  end

  def new
    @post = Post.new
  end

  def edit
    @post = Post.find(params[:id])
  end

  def create
    @post = current_user.posts.build(post_params)
    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: "投稿を削除しました" }
      format.json { head :no_content }
    end
  end
  def confirm
    @post = current_user.posts.build(post_params)
    render :new if @post.invalid?
  end

  private
  def set_post
    @post = Post.find(params[:id])
  end
  def post_params
    params.require(:post).permit(:title, :content, :image, :image_cache,:user_id)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    skip_before_action :login_required, only: [:new, :create]
    def new
    end
    def create
      user = User.find_by(email: params[:session][:email].downcase)
      if user && user.authenticate(params[:session][:password])
        session[:user_id] = user.id
        redirect_to user_path(user.id)
      else
        flash.now[:danger] = 'I failed to login'
        render :new
      end
    end
    def destroy
      session.delete(:user_id)
      flash[:notice] = 'logged out'
      redirect_to new_session_path
    end
  end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    skip_before_action :login_required, only: [:new, :create]
    def new
      @user = User.new
    end
    def create
      @user = User.new(user_params)
      if @user.save
          redirect_to user_path(@user.id)
      else
      render :new
      end
    end
    def show
      @user = User.find(params[:id])
    end
    private
    def user_params
      params.require(:user).permit(:name, :email, :password,
      :password_confirmation)
    end
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
    def choose_new_or_edit
      if action_name == 'new'
        confirm_posts_path
      elsif action_name == 'edit'
        post_path
      end
    end
  end

app/helpers/sessions_helper.rb
module SessionsHelper
    def current_user
      @current_user ||= User.find_by(id: session[:user_id])
    end
    def logged_in?
      current_user.present?
    end
  end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FacebookClone</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body style="background:#e9ebee">
  <nav class="navbar navbar-expand-lg sticky-top navbar-light" style="background-color: #3c5a98;color:white">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo03" aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
  <span class="navbar-toggler-icon"></span>
  </button>
  <a class="navbar-brand" href="#" style="color:white;font-size:40px;margin-left:153px"><b>facebook</b></a>
  
  <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
    <form class="form-inline my-2 my-lg-0">
      <% if logged_in? %>
        <button style="background-color:navy;text-color:white;border:1px solid black;border-radius:5px;margin-left:800px"><%= link_to "Profile", user_path(current_user.id) %></button>
        <button style="background-color:navy;text-color:white;border:1px solid black;border-radius:5px;margin-left:10px"><%= link_to "Logout", session_path(current_user.id), method: :delete %></button>
      <% else %>
        <button style="background-color:navy;text-color:white;border:1px solid black;border-radius:5px;margin-left:800px"><%= link_to "Login", new_session_path %></button>
        <button style="background-color:navy;text-color:white;border:1px solid black;border-radius:5px;margin-left:10px"><%= link_to "SignUp", new_user_path %></button>
      <% end %>
    </form>
  </div>
  </nav>
  
  <% flash.each do |key, value| %>
    <%= content_tag(:div, value, class: "#{key}") %>
  <% end %>
   
  <%= yield %>
  </body>
  </html>
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  

app/views/posts/_form.html.erb
<%= form_with(model: @post, local: true ,url: choose_new_or_edit ) do |form| %>
    <% if @post.errors.any? %>
      <div id="error_explanation">
        <h2><%= @post.errors.count %>There are some errors.</h2>
        <ul>
        <% @post.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
    <div class="field">
      <%= form.label :content %>
      <%= form.text_field :content %>
    </div>
    <div class="field">
      <%= image_tag(@post.image.url) if @post.image && @post.image.url %>
      <%= form.label :image %>
      <%= form.file_field :image %>
      <%= form.hidden_field :image_cache %>
    </div>
    <%= form.submit %>
  <% end %>
  end

app/views/posts/confirm.html.erb
<h3>confirmation screen</h3>
<%= form_with(model: @post, local: true) do |form| %>
  <%= form.hidden_field :title %>
  <%= form.hidden_field :content %>
  <%= form.hidden_field :image_cache %>
  <p>title：<%= @post.title %></p>
  <p>content：<%= @post.content %></p>
  <p>image：<%= image_tag @post.image.url %></p>
  <%= form.submit "confirm" %>
<% end %>

app/views/posts/edit.html.erb
<h1>Edit screen</h1>

<%= render 'form', post: @post %>

<%= link_to 'show', @post %> |
<%= link_to 'back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>posts</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>content</th>
      <th>image</th>
      <th>Posted by</th>
      <th colspan="3">Action</th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.content %></td>
        <td><%= image_tag post.image.url, style:"width:500px" %></td>
        <td><%= post.user.name %></td>
        <td><%= link_to 'show', post %></td>
        <td><%= link_to 'edit', edit_post_path(post) %></td>
        <td><%= link_to 'delete', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'new post', new_post_path %>

app/views/posts/new.html.erb
<div id="main2">
  <div id="left">
    &nbsp
  </div>
  <div id="content">
    <div class="content-content">
      <hr>
      <h1>New Post</h1>
      <hr>
      <%= render 'form', post: @post %><br>
      <%= link_to 'Back', posts_path,class:'btn btn-primary' %>
    </div>
  <div id="right"></div>
  </div>
</div>

app/views/posts/show.html.erb
<div id="main2">
  <div id="left">
    &nbsp
  </div>
  <div id="content">
    <div class="content-content">
      <hr>
      <p id="notice"><%= notice %></p>
      <hr>
      <p class="names">
      <strong>Posted by:</strong>
      <%= @post.user.name %> 
      </p>
      <p>
      <strong>Content:</strong>
      <%= @post.content %>
      </p>
      <p>
      <strong>Image:</strong>
      <%= image_tag @post.image.url, style:"width:500px" %>
      </p>
      <%= link_to 'Back', posts_path,class:'btn btn-primary' %>
    </div>
  <div id="right"></div>
  </div>
</div>


app/views/shared/_footer.html.erb
<h1> Facebook.com </h1>

app/views/shared/_header.html.erb
<h1>Facebook</h1>

app/views/users/new.html.erb
<h1>sign up</h1>
<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this <%= @user.name %> from being saved:</h2>
    <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>
<%= form_with(model: @user, local: true) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :email %>
  <%= f.email_field :email %>
  <%= f.label :password %>
  <%= f.password_field :password %>
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %><br>
  <br>
  <%= f.submit "Create my account" %>
<% end %>

app/views/users/show.html.erb
<h1><%= @user.name %>page of</h1>
<p>emailス: <%= @user.email %></p>